$image = /home/ducky/Pictures/Background/QvevW8JVDf.png


$background = rgba(111416ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2e3133ff)

$inverse_primary = rgba(1f6489ff)

$inverse_surface = rgba(e1e2e6ff)

$on_background = rgba(e1e2e6ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(00344cff)

$on_primary_container = rgba(ebf5ffff)

$on_primary_fixed = rgba(001e2eff)

$on_primary_fixed_variant = rgba(004c6cff)

$on_secondary = rgba(1d3341ff)

$on_secondary_container = rgba(d0e7faff)

$on_secondary_fixed = rgba(061e2bff)

$on_secondary_fixed_variant = rgba(344958ff)

$on_surface = rgba(e1e2e6ff)

$on_surface_variant = rgba(c0c7cfff)

$on_tertiary = rgba(482900ff)

$on_tertiary_container = rgba(fff2e8ff)

$on_tertiary_fixed = rgba(2b1700ff)

$on_tertiary_fixed_variant = rgba(673d00ff)

$outline = rgba(8a9298ff)

$outline_variant = rgba(40484eff)

$primary = rgba(91cef7ff)

$primary_container = rgba(08587cff)

$primary_fixed = rgba(c7e7ffff)

$primary_fixed_dim = rgba(91cef7ff)

$scrim = rgba(000000ff)

$secondary = rgba(b3c9dbff)

$secondary_container = rgba(364c5bff)

$secondary_fixed = rgba(cfe5f8ff)

$secondary_fixed_dim = rgba(b3c9dbff)

$shadow = rgba(000000ff)

$source_color = rgba(08587cff)

$surface = rgba(111416ff)

$surface_bright = rgba(37393cff)

$surface_container = rgba(1d2022ff)

$surface_container_high = rgba(272a2dff)

$surface_container_highest = rgba(323538ff)

$surface_container_low = rgba(191c1eff)

$surface_container_lowest = rgba(0c0f11ff)

$surface_dim = rgba(111416ff)

$surface_tint = rgba(91cef7ff)

$surface_variant = rgba(40484eff)

$tertiary = rgba(fbba70ff)

$tertiary_container = rgba(764805ff)

$tertiary_fixed = rgba(ffddbbff)

$tertiary_fixed_dim = rgba(fbba70ff)

