require("modules.monitors")
require("modules.programs")
require("modules.autostart")
require("modules.env")
require("modules.decoration")
require("modules.animations")
require("modules.windowrules")
require("modules.layout")
require("modules.misc")
require("modules.input")
require("modules.binds")
require("modules.monitors")
require("colors")
  