# : Manager [[[

[mgr]
cwd = { fg = "#e1e2e6" }

# Tab
tab_active = { fg = "#00344c", bg = "#91cef7", bold = true }
tab_inactive = { fg = "#c7e7ff", bg = "#001e2e" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffaa55", bg = "#ffaa55" }
marker_cut = { fg = "#ffddbb", bg = "#ffddbb" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#fbba70", bg = "#fbba70" }

# Count
count_copied = { fg = "#2b1700", bg = "#ffddbb" }
count_cut = { fg = "#2b1700", bg = "#ffddbb" }
count_selected = { fg = "#00344c", bg = "#fbba70" }

# Border
border_symbol = " "
border_style  = { fg = "#91cef7" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#00344c", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#91cef7", fg = "#00344c", bold = true }
normal_alt  = { bg = "#40484e", fg = "#c0c7cf" }

# Select mode
select_main = { bg = "#b3c9db", fg = "#1d3341", bold = true }
select_alt  = { bg = "#40484e", fg = "#c0c7cf" }

# Unset mode
unset_main = { bg = "#fbba70", fg = "#482900", bold = true }
unset_alt  = { bg = "#40484e", fg = "#c0c7cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#91cef7", bg = "#37393c" }
progress_error = { fg = "#ffb4ab", bg = "#37393c" }

# Permissions
permissions_t = { fg = "#4f7fa6" }
permissions_w = { fg = "#cc6f06" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff9122" }
permissions_s = { fg = "#2ea5ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#91cef7" }
active = { fg = "#fbba70", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#91cef7" }
value = { fg = "#e1e2e6" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#91cef7", bold = true, bg = "#111416" }
inactive = { fg = "#b3c9db", bg = "#111416" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#91cef7", bg = "#00344c" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#91cef7" }
title = {}
hovered = { fg = "#ffddbb", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#37393c" }
cand = { fg = "#91cef7" }
rest = { fg = "#00344c" }
desc = { fg = "#e1e2e6" }
separator = " ▶ "
separator_style = { fg = "#e1e2e6" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e1e2e6" }
run = { fg = "#e1e2e6" }
footer = { fg = "#1d3341", bg = "#b3c9db" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#fbba70" }
title_warn = { fg = "#91cef7" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e1e2e6" },
    { name = "*/", fg = "#91cef7" },
]

# : ]]]
